assign_factor_vars <- function(idata) {
    idata <- idata %>% mutate(AGEGRP = factor(AGEGRP, 
                                              levels = AGEGRPlevels, 
                                              labels = AGEGRPlabels))
    idata <- idata %>% mutate(LANGUAGE = factor(LANGUAGE, 
                                                levels = LANGUAGElevels,
                                                labels = LANGUAGElabels))
    idata <- idata %>% mutate(HAD_CPOX = factor(HAD_CPOX, 
                                                levels = YNDKRFlevels, 
                                                labels = YNDKRFlabels))
    idata <- idata %>% mutate(CWIC_02 = factor(CWIC_02, levels = YNDKRFlevels, labels = YNDKRFlabels))
    idata <- idata %>% mutate(CBF_01 = factor(CBF_01, levels = YNDKRFlevels, labels = YNDKRFlabels))
    
    idata <- idata %>% mutate(P_NUHEPX = factor(P_NUHEPX, levels = SHOTCOUNlevels, labels = SHOTCOUNlabels))
    idata <- idata %>% mutate(U3D_HEP = factor(U3D_HEP, levels = SHOTCOUNlevels, labels = SHOTCOUNlabels))
    idata <- idata %>% mutate(U2D_HEP = factor(U2D_HEP, levels = SHOTCOUNlevels, labels = SHOTCOUNlabels))
    idata <- idata %>% mutate(U1D_HEP = factor(U1D_HEP, levels = SHOTCOUNlevels, labels = SHOTCOUNlabels))
    idata <- idata %>% mutate(P_UTDHEPA1 = factor(P_UTDHEPA1, levels = SHOTCOUNlevels, labels = SHOTCOUNlabels))
    
    idata <- idata %>% mutate(P_NUMVRX = factor(P_NUMVRX, levels = SHOTCOUNlevels, labels = SHOTCOUNlabels))
    idata <- idata %>% mutate(P_NUMVRN = factor(P_NUMVRN, levels = SHOTCOUNlevels, labels = SHOTCOUNlabels))
    idata <- idata %>% mutate(P_NUMVRC = factor(P_NUMVRC, levels = SHOTCOUNlevels, labels = SHOTCOUNlabels))
    idata <- idata %>% mutate(P_NUMTPN = factor(P_NUMTPN, levels = SHOTCOUNlevels, labels = SHOTCOUNlabels))
    idata <- idata %>% mutate(P_NUMROT = factor(P_NUMROT, levels = SHOTCOUNlevels, labels = SHOTCOUNlabels))
    
    idata <- idata %>% mutate(P_NUMRO = factor(P_NUMRO, levels = SHOTCOUNlevels, labels = SHOTCOUNlabels))
    idata <- idata %>% mutate(P_NUMRM = factor(P_NUMRM, levels = SHOTCOUNlevels, labels = SHOTCOUNlabels))
    idata <- idata %>% mutate(P_NUMRG = factor(P_NUMRG, levels = SHOTCOUNlevels, labels = SHOTCOUNlabels))
    idata <- idata %>% mutate(P_NUMRB = factor(P_NUMRB, levels = SHOTCOUNlevels, labels = SHOTCOUNlabels))
    idata <- idata %>% mutate(P_NUMPOL = factor(P_NUMPOL, levels = SHOTCOUNlevels, labels = SHOTCOUNlabels))
    
    idata <- idata %>% mutate(P_NUMPCN = factor(P_NUMPCN, levels = SHOTCOUNlevels, labels = SHOTCOUNlabels))
    idata <- idata %>% mutate(P_NUMPCCN = factor(P_NUMPCCN, levels = SHOTCOUNlevels, labels = SHOTCOUNlabels))
    idata <- idata %>% mutate(P_NUMPCC13 = factor(P_NUMPCC13, levels = SHOTCOUNlevels, labels = SHOTCOUNlabels))
    idata <- idata %>% mutate(P_NUMPCC7 = factor(P_NUMPCC7, levels = SHOTCOUNlevels, labels = SHOTCOUNlabels))
    idata <- idata %>% mutate(P_NUMPCC = factor(P_NUMPCC, levels = SHOTCOUNlevels, labels = SHOTCOUNlabels))
    
    idata <- idata %>% mutate(P_NUMPCP = factor(P_NUMPCP, levels = SHOTCOUNlevels, labels = SHOTCOUNlabels))
    idata <- idata %>% mutate(P_NUMPCV = factor(P_NUMPCV, levels = SHOTCOUNlevels, labels = SHOTCOUNlabels))
    idata <- idata %>% mutate(P_NUMOPV = factor(P_NUMOPV, levels = SHOTCOUNlevels, labels = SHOTCOUNlabels))
    idata <- idata %>% mutate(P_NUMOLN = factor(P_NUMOLN, levels = SHOTCOUNlevels, labels = SHOTCOUNlabels))
    idata <- idata %>% mutate(P_NUMMSR = factor(P_NUMMSR, levels = SHOTCOUNlevels, labels = SHOTCOUNlabels))
    
    idata <- idata %>% mutate(P_NUMMSM = factor(P_NUMMSM, levels = SHOTCOUNlevels, labels = SHOTCOUNlabels))
    idata <- idata %>% mutate(P_NUMMS = factor(P_NUMMS, levels = SHOTCOUNlevels, labels = SHOTCOUNlabels))
    idata <- idata %>% mutate(P_NUMMRV = factor(P_NUMMRV, levels = SHOTCOUNlevels, labels = SHOTCOUNlabels))
    idata <- idata %>% mutate(P_NUMMPR = factor(P_NUMMPR, levels = SHOTCOUNlevels, labels = SHOTCOUNlabels))
    idata <- idata %>% mutate(P_NUMMP = factor(P_NUMMP, levels = SHOTCOUNlevels, labels = SHOTCOUNlabels))
    
    idata <- idata %>% mutate(P_NUMMMX = factor(P_NUMMMX, levels = SHOTCOUNlevels, labels = SHOTCOUNlabels))
    idata <- idata %>% mutate(P_NUMMMRX = factor(P_NUMMMRX, levels = SHOTCOUNlevels, labels = SHOTCOUNlabels))
    idata <- idata %>% mutate(P_NUMMMR = factor(P_NUMMMR, levels = SHOTCOUNlevels, labels = SHOTCOUNlabels))
    idata <- idata %>% mutate(P_NUMMCN = factor(P_NUMMCN, levels = SHOTCOUNlevels, labels = SHOTCOUNlabels))
    idata <- idata %>% mutate(P_NUMIPV = factor(P_NUMIPV, levels = SHOTCOUNlevels, labels = SHOTCOUNlabels))
    
    idata <- idata %>% mutate(P_NUMHS = factor(P_NUMHS, levels = SHOTCOUNlevels, labels = SHOTCOUNlabels))
    idata <- idata %>% mutate(P_NUMHM = factor(P_NUMHM, levels = SHOTCOUNlevels, labels = SHOTCOUNlabels))
    idata <- idata %>% mutate(P_NUMHION = factor(P_NUMHION, levels = SHOTCOUNlevels, labels = SHOTCOUNlabels))
    idata <- idata %>% mutate(P_NUMHIN = factor(P_NUMHIN, levels = SHOTCOUNlevels, labels = SHOTCOUNlabels))
    idata <- idata %>% mutate(P_NUMHIB = factor(P_NUMHIB, levels = SHOTCOUNlevels, labels = SHOTCOUNlabels))
    
    idata <- idata %>% mutate(P_NUMHHY = factor(P_NUMHHY, levels = SHOTCOUNlevels, labels = SHOTCOUNlabels))
    idata <- idata %>% mutate(P_NUMHG = factor(P_NUMHG, levels = SHOTCOUNlevels, labels = SHOTCOUNlabels))
    idata <- idata %>% mutate(P_NUMHEP = factor(P_NUMHEP, levels = SHOTCOUNlevels, labels = SHOTCOUNlabels))
    idata <- idata %>% mutate(P_NUMHEN = factor(P_NUMHEN, levels = SHOTCOUNlevels, labels = SHOTCOUNlabels))
    idata <- idata %>% mutate(P_NUMHEA = factor(P_NUMHEA, levels = SHOTCOUNlevels, labels = SHOTCOUNlabels))
    
    idata <- idata %>% mutate(P_NUMFLUN = factor(P_NUMFLUN, levels = SHOTCOUNlevels, labels = SHOTCOUNlabels))
    idata <- idata %>% mutate(P_NUMFLUM = factor(P_NUMFLUM, levels = SHOTCOUNlevels, labels = SHOTCOUNlabels))
    idata <- idata %>% mutate(P_NUMFLUL = factor(P_NUMFLUL, levels = SHOTCOUNlevels, labels = SHOTCOUNlabels))
    idata <- idata %>% mutate(P_NUMFLU = factor(P_NUMFLU, levels = SHOTCOUNlevels, labels = SHOTCOUNlabels))
    idata <- idata %>% mutate(P_NUMDTP = factor(P_NUMDTP, levels = SHOTCOUNlevels, labels = SHOTCOUNlabels))
    
    idata <- idata %>% mutate(P_NUMDTA = factor(P_NUMDTA, levels = SHOTCOUNlevels, labels = SHOTCOUNlabels))
    idata <- idata %>% mutate(P_NUMDIH = factor(P_NUMDIH, levels = SHOTCOUNlevels, labels = SHOTCOUNlabels))
    idata <- idata %>% mutate(P_NUMDHI = factor(P_NUMDHI, levels = SHOTCOUNlevels, labels = SHOTCOUNlabels))
    idata <- idata %>% mutate(P_NUMDAH = factor(P_NUMDAH, levels = SHOTCOUNlevels, labels = SHOTCOUNlabels))
    idata <- idata %>% mutate(P_NUHPHB = factor(P_NUHPHB, levels = SHOTCOUNlevels, labels = SHOTCOUNlabels))
    
    idata <- idata %>% mutate(P_NUHIBX = factor(P_NUHIBX, levels = SHOTCOUNlevels, labels = SHOTCOUNlabels))
    idata <- idata %>% mutate(D7 = factor(D7, levels = YNlevels, labels = YNlabels))
    idata <- idata %>% mutate(BFENDFL06 = factor(BFENDFL06, levels = Ylevels, labels = Ylabels))
    idata <- idata %>% mutate(BFFORMFL06 = factor(BFFORMFL06, levels = Ylevels, labels = Ylabels))
    idata <- idata %>% mutate(CHILDNM = factor(CHILDNM, levels = CHILDNMlevels, labels = CHILDNMlabels))
    
    idata <- idata %>% mutate(CWIC_01 = factor(CWIC_01, levels = CWIClevels, labels = CWIClabels))
    idata <- idata %>% mutate(EDUC1 = factor(EDUC1, levels = EDUC1_levels, labels = EDUC1_labels))
    idata <- idata %>% mutate(I_HISP_K = factor(I_HISP_K, levels = HISPlevels, labels = HISPlabels))
    idata <- idata %>% mutate(MOBIL_I = factor(MOBIL_I, levels = MOBILlevels, labels = MOBILlabels))
    idata <- idata %>% mutate(SEX = factor(SEX, levels = SEXlevels, labels = SEXlabels))
    
    idata <- idata %>% mutate(INCPOV1 = factor(INCPOV1, levels = INCPOVlevels, labels = INCPOVlabels))
    idata <- idata %>% mutate(PDAT = factor(PDAT, levels = HASPDA2Flevels, labels = HASPDA2Flabels))
    idata <- idata %>% mutate(PROV_FAC = factor(PROV_FAC, levels = PROVIDlevels, labels = PROVIDlabels))
    idata <- idata %>% mutate(REGISTRY = factor(REGISTRY, levels = REGISTRYlevels, labels = REGISTRYlabels))
    idata <- idata %>% mutate(VFC_ORDER = factor(VFC_ORDER, levels = REGISTRYlevels, labels = REGISTRYlabels))
    
    idata <- idata %>% mutate(XDTPTY1 = factor(XDTPTY1, levels = TYPElevels, labels = TYPElabels))
    idata <- idata %>% mutate(XVRCTY9 = factor(XVRCTY9, levels = TYPElevels, labels = TYPElabels))
    idata <- idata %>% mutate(XVRCTY8 = factor(XVRCTY8, levels = TYPElevels, labels = TYPElabels))
    idata <- idata %>% mutate(XVRCTY7 = factor(XVRCTY7, levels = TYPElevels, labels = TYPElabels))
    idata <- idata %>% mutate(XVRCTY6 = factor(XVRCTY6, levels = TYPElevels, labels = TYPElabels))
    
    idata <- idata %>% mutate(XVRCTY5 = factor(XVRCTY5, levels = TYPElevels, labels = TYPElabels))
    idata <- idata %>% mutate(XVRCTY4 = factor(XVRCTY4, levels = TYPElevels, labels = TYPElabels))
    idata <- idata %>% mutate(XVRCTY3 = factor(XVRCTY3, levels = TYPElevels, labels = TYPElabels))
    idata <- idata %>% mutate(XVRCTY2 = factor(XVRCTY2, levels = TYPElevels, labels = TYPElabels))
    idata <- idata %>% mutate(XVRCTY1 = factor(XVRCTY1, levels = TYPElevels, labels = TYPElabels))
    
    idata <- idata %>% mutate(XROTTY9 = factor(XROTTY9, levels = TYPElevels, labels = TYPElabels))
    idata <- idata %>% mutate(XROTTY8 = factor(XROTTY8, levels = TYPElevels, labels = TYPElabels))
    idata <- idata %>% mutate(XROTTY7 = factor(XROTTY7, levels = TYPElevels, labels = TYPElabels))
    idata <- idata %>% mutate(XROTTY6 = factor(XROTTY6, levels = TYPElevels, labels = TYPElabels))
    idata <- idata %>% mutate(XROTTY5 = factor(XROTTY5, levels = TYPElevels, labels = TYPElabels))
    
    idata <- idata %>% mutate(XROTTY4 = factor(XROTTY4, levels = TYPElevels, labels = TYPElabels))
    idata <- idata %>% mutate(XROTTY3 = factor(XROTTY3, levels = TYPElevels, labels = TYPElabels))
    idata <- idata %>% mutate(XROTTY2 = factor(XROTTY2, levels = TYPElevels, labels = TYPElabels))
    idata <- idata %>% mutate(XROTTY1 = factor(XROTTY1, levels = TYPElevels, labels = TYPElabels))
    idata <- idata %>% mutate(XPOLTY9 = factor(XPOLTY9, levels = TYPElevels, labels = TYPElabels))
    
    idata <- idata %>% mutate(XPOLTY8 = factor(XPOLTY8, levels = TYPElevels, labels = TYPElabels))
    idata <- idata %>% mutate(XPOLTY7 = factor(XPOLTY7, levels = TYPElevels, labels = TYPElabels))
    idata <- idata %>% mutate(XPOLTY6 = factor(XPOLTY6, levels = TYPElevels, labels = TYPElabels))
    idata <- idata %>% mutate(XPOLTY5 = factor(XPOLTY5, levels = TYPElevels, labels = TYPElabels))
    idata <- idata %>% mutate(XPOLTY4 = factor(XPOLTY4, levels = TYPElevels, labels = TYPElabels))
    
    idata <- idata %>% mutate(XPOLTY3 = factor(XPOLTY3, levels = TYPElevels, labels = TYPElabels))
    idata <- idata %>% mutate(XPOLTY2 = factor(XPOLTY2, levels = TYPElevels, labels = TYPElabels))
    idata <- idata %>% mutate(XPOLTY1 = factor(XPOLTY1, levels = TYPElevels, labels = TYPElabels))
    idata <- idata %>% mutate(XPCVTY9 = factor(XPCVTY9, levels = TYPElevels, labels = TYPElabels))
    idata <- idata %>% mutate(XPCVTY8 = factor(XPCVTY8, levels = TYPElevels, labels = TYPElabels))
    
    idata <- idata %>% mutate(XPCVTY7 = factor(XPCVTY7, levels = TYPElevels, labels = TYPElabels))
    idata <- idata %>% mutate(XPCVTY6 = factor(XPCVTY6, levels = TYPElevels, labels = TYPElabels))
    idata <- idata %>% mutate(XPCVTY5 = factor(XPCVTY5, levels = TYPElevels, labels = TYPElabels))
    idata <- idata %>% mutate(XPCVTY4 = factor(XPCVTY4, levels = TYPElevels, labels = TYPElabels))
    idata <- idata %>% mutate(XPCVTY3 = factor(XPCVTY3, levels = TYPElevels, labels = TYPElabels))
    
    idata <- idata %>% mutate(XPCVTY2 = factor(XPCVTY2, levels = TYPElevels, labels = TYPElabels))
    idata <- idata %>% mutate(XPCVTY1 = factor(XPCVTY1, levels = TYPElevels, labels = TYPElabels))
    idata <- idata %>% mutate(XMMRTY9 = factor(XMMRTY9, levels = TYPElevels, labels = TYPElabels))
    idata <- idata %>% mutate(XMMRTY8 = factor(XMMRTY8, levels = TYPElevels, labels = TYPElabels))
    idata <- idata %>% mutate(XMMRTY7 = factor(XMMRTY7, levels = TYPElevels, labels = TYPElabels))
    
    idata <- idata %>% mutate(XMMRTY6 = factor(XMMRTY6, levels = TYPElevels, labels = TYPElabels))
    idata <- idata %>% mutate(XMMRTY5 = factor(XMMRTY5, levels = TYPElevels, labels = TYPElabels))
    idata <- idata %>% mutate(XMMRTY4 = factor(XMMRTY4, levels = TYPElevels, labels = TYPElabels))
    idata <- idata %>% mutate(XMMRTY3 = factor(XMMRTY3, levels = TYPElevels, labels = TYPElabels))
    idata <- idata %>% mutate(XMMRTY2 = factor(XMMRTY2, levels = TYPElevels, labels = TYPElabels))
    
    idata <- idata %>% mutate(XMMRTY1 = factor(XMMRTY1, levels = TYPElevels, labels = TYPElabels))
    idata <- idata %>% mutate(XHIBTY9 = factor(XHIBTY9, levels = TYPElevels, labels = TYPElabels))
    idata <- idata %>% mutate(XHIBTY8 = factor(XHIBTY8, levels = TYPElevels, labels = TYPElabels))
    idata <- idata %>% mutate(XHIBTY7 = factor(XHIBTY7, levels = TYPElevels, labels = TYPElabels))
    idata <- idata %>% mutate(XHIBTY6 = factor(XHIBTY6, levels = TYPElevels, labels = TYPElabels))
    
    idata <- idata %>% mutate(XHIBTY5 = factor(XHIBTY5, levels = TYPElevels, labels = TYPElabels))
    idata <- idata %>% mutate(XHIBTY4 = factor(XHIBTY4, levels = TYPElevels, labels = TYPElabels))
    idata <- idata %>% mutate(XHIBTY3 = factor(XHIBTY3, levels = TYPElevels, labels = TYPElabels))
    idata <- idata %>% mutate(XHIBTY2 = factor(XHIBTY2, levels = TYPElevels, labels = TYPElabels))
    idata <- idata %>% mutate(XHIBTY1 = factor(XHIBTY1, levels = TYPElevels, labels = TYPElabels))
    
    idata <- idata %>% mutate(XHEPTY9 = factor(XHEPTY9, levels = TYPElevels, labels = TYPElabels))
    idata <- idata %>% mutate(XHEPTY8 = factor(XHEPTY8, levels = TYPElevels, labels = TYPElabels))
    idata <- idata %>% mutate(XHEPTY7 = factor(XHEPTY7, levels = TYPElevels, labels = TYPElabels))
    idata <- idata %>% mutate(XHEPTY6 = factor(XHEPTY6, levels = TYPElevels, labels = TYPElabels))
    idata <- idata %>% mutate(XHEPTY5 = factor(XHEPTY5, levels = TYPElevels, labels = TYPElabels))
    
    idata <- idata %>% mutate(XHEPTY4 = factor(XHEPTY4, levels = TYPElevels, labels = TYPElabels))
    idata <- idata %>% mutate(XHEPTY3 = factor(XHEPTY3, levels = TYPElevels, labels = TYPElabels))
    idata <- idata %>% mutate(XHEPTY2 = factor(XHEPTY2, levels = TYPElevels, labels = TYPElabels))
    idata <- idata %>% mutate(XHEPTY1 = factor(XHEPTY1, levels = TYPElevels, labels = TYPElabels))
    idata <- idata %>% mutate(XFLUTY9 = factor(XFLUTY9, levels = TYPElevels, labels = TYPElabels))
    
    idata <- idata %>% mutate(XFLUTY8 = factor(XFLUTY8, levels = TYPElevels, labels = TYPElabels))
    idata <- idata %>% mutate(XFLUTY7 = factor(XFLUTY7, levels = TYPElevels, labels = TYPElabels))
    idata <- idata %>% mutate(XFLUTY6 = factor(XFLUTY6, levels = TYPElevels, labels = TYPElabels))
    idata <- idata %>% mutate(XFLUTY5 = factor(XFLUTY5, levels = TYPElevels, labels = TYPElabels))
    idata <- idata %>% mutate(XFLUTY4 = factor(XFLUTY4, levels = TYPElevels, labels = TYPElabels))
    
    idata <- idata %>% mutate(XFLUTY3 = factor(XFLUTY3, levels = TYPElevels, labels = TYPElabels))
    idata <- idata %>% mutate(XFLUTY2 = factor(XFLUTY2, levels = TYPElevels, labels = TYPElabels))
    idata <- idata %>% mutate(XFLUTY1 = factor(XFLUTY1, levels = TYPElevels, labels = TYPElabels))
    idata <- idata %>% mutate(XDTPTY9 = factor(XDTPTY9, levels = TYPElevels, labels = TYPElabels))
    idata <- idata %>% mutate(XDTPTY8 = factor(XDTPTY8, levels = TYPElevels, labels = TYPElabels))
    
    idata <- idata %>% mutate(XDTPTY7 = factor(XDTPTY7, levels = TYPElevels, labels = TYPElabels))
    idata <- idata %>% mutate(XDTPTY6 = factor(XDTPTY6, levels = TYPElevels, labels = TYPElabels))
    idata <- idata %>% mutate(XDTPTY5 = factor(XDTPTY5, levels = TYPElevels, labels = TYPElabels))
    idata <- idata %>% mutate(XDTPTY4 = factor(XDTPTY4, levels = TYPElevels, labels = TYPElabels))
    idata <- idata %>% mutate(XDTPTY3 = factor(XDTPTY3, levels = TYPElevels, labels = TYPElabels))
    
    idata <- idata %>% mutate(XDTPTY2 = factor(XDTPTY2, levels = TYPElevels, labels = TYPElabels))
    idata <- idata %>% mutate(HEP_BRTH = factor(HEP_BRTH, levels = HEPBRTlevels, labels = HEPBRTlabels))
    idata <- idata %>% mutate(HEP_FLAG = factor(HEP_FLAG, levels = HEPFLGlevels, labels = HEPFLGlabels))
    idata <- idata %>% mutate(P_U12VRC = factor(P_U12VRC, levels = UTDlevels, labels = UTDlabels))
    idata <- idata %>% mutate(P_UTD431H_ROUT_S = factor(P_UTD431H_ROUT_S, levels = UTDlevels, labels = UTDlabels))
    
    idata <- idata %>% mutate(PUTD4313 = factor(PUTD4313, levels = UTDlevels, labels = UTDlabels))
    idata <- idata %>% mutate(P_UTD431H3_ROUT_S = factor(P_UTD431H3_ROUT_S, levels = UTDlevels, labels = UTDlabels))
    idata <- idata %>% mutate(PUT43133 = factor(PUT43133, levels = UTDlevels, labels = UTDlabels))
    idata <- idata %>% mutate(PU431_314 = factor(PU431_314, levels = UTDlevels, labels = UTDlabels))
    idata <- idata %>% mutate(P_UTD431H314_ROUT_S = factor(P_UTD431H314_ROUT_S, levels = UTDlevels, labels = UTDlabels))
    
    idata <- idata %>% mutate(PU4313314 = factor(PU4313314, levels = UTDlevels, labels = UTDlabels))
    idata <- idata %>% mutate(P_UTD431H313_ROUT_S = factor(P_UTD431H313_ROUT_S, levels = UTDlevels, labels = UTDlabels))
    idata <- idata %>% mutate(PU4313313 = factor(PU4313313, levels = UTDlevels, labels = UTDlabels))
    idata <- idata %>% mutate(PU431_31 = factor(PU431_31, levels = UTDlevels, labels = UTDlabels))
    idata <- idata %>% mutate(P_UTD431H31_ROUT_S = factor(P_UTD431H31_ROUT_S, levels = UTDlevels, labels = UTDlabels))
    
    idata <- idata %>% mutate(PU431331 = factor(PU431331, levels = UTDlevels, labels = UTDlabels))
    idata <- idata %>% mutate(P_UTDTP4 = factor(P_UTDTP4, levels = UTDlevels, labels = UTDlabels))
    idata <- idata %>% mutate(P_UTDTP3 = factor(P_UTDTP3, levels = UTDlevels, labels = UTDlabels))
    idata <- idata %>% mutate(P_UTDROT_S = factor(P_UTDROT_S, levels = UTDlevels, labels = UTDlabels))
    idata <- idata %>% mutate(P_UTDPOL = factor(P_UTDPOL, levels = UTDlevels, labels = UTDlabels))
    
    idata <- idata %>% mutate(P_UTDPCV = factor(P_UTDPCV, levels = UTDlevels, labels = UTDlabels))
    idata <- idata %>% mutate(P_UTDPC3 = factor(P_UTDPC3, levels = UTDlevels, labels = UTDlabels))
    idata <- idata %>% mutate(P_UTDMMX = factor(P_UTDMMX, levels = UTDlevels, labels = UTDlabels))
    idata <- idata %>% mutate(P_UTDMCV = factor(P_UTDMCV, levels = UTDlevels, labels = UTDlabels))
    idata <- idata %>% mutate(P_UTDHIB_SHORT_S = factor(P_UTDHIB_SHORT_S, levels = UTDlevels, labels = UTDlabels))
    
    idata <- idata %>% mutate(P_UTDHIB_ROUT_S = factor(P_UTDHIB_ROUT_S, levels = UTDlevels, labels = UTDlabels))
    idata <- idata %>% mutate(P_UTDHIB = factor(P_UTDHIB, levels = UTDlevels, labels = UTDlabels))
    idata <- idata %>% mutate(P_UTDHEPA2 = factor(P_UTDHEPA2, levels = UTDlevels, labels = UTDlabels))
    idata <- idata %>% mutate(P_UTDHEP = factor(P_UTDHEP, levels = UTDlevels, labels = UTDlabels))
    idata <- idata %>% mutate(P_UTD431 = factor(P_UTD431, levels = UTDlevels, labels = UTDlabels))
    
    idata <- idata %>% mutate(P_UTD331 = factor(P_UTD331, levels = UTDlevels, labels = UTDlabels))
    idata <- idata %>% mutate(CEN_REG = factor(CEN_REG, levels = CENREGlevels, labels = CENREGlabels))
    idata <- idata %>% mutate(STATE = factor(STATE, levels = STATElevels, labels = STATElabels))
    idata <- idata %>% mutate(RACE_K = factor(RACE_K, levels = RACE_PUFlevels, labels = RACE_PUFlabels))
    idata <- idata %>% mutate(AGECPOXR = factor(AGECPOXR, levels = AGECPOXRlevels, labels = AGECPOXRlabels))
    
    idata <- idata %>% mutate(C1R = factor(C1R, levels = C1Rlevels, labels = C1Rlabels))
    idata <- idata %>% mutate(C5R = factor(C5R, levels = C5Rlevels, labels = C5Rlabels))
    idata <- idata %>% mutate(INCQ298A = factor(INCQ298A, levels = INCQ298Alevels, labels = INCQ298Alabels))
    idata <- idata %>% mutate(RACEETHK = factor(RACEETHK, levels = RACEETHKlevels, labels = RACEETHKlabels))
    idata <- idata %>% mutate(D6R = factor(D6R, levels = D6Rlevels, labels = D6Rlabels))
    
    idata <- idata %>% mutate(N_PRVR = factor(N_PRVR, levels = D6Rlevels, labels = D6Rlabels))
    idata <- idata %>% mutate(FRSTBRN = factor(FRSTBRN, levels = FRSTBRNlevels, labels = FRSTBRNlabels))
    idata <- idata %>% mutate(BF_FORMR08 = factor(BF_FORMR08, levels = BFFORM08Flevels, labels = BFFORM08Flabels))
    
    idata <- idata %>% mutate(RENT_OWN = factor(RENT_OWN, levels = RENTOWNlevels, labels = RENTOWNlabels))
    idata <- idata %>% mutate(NUM_PHONE = factor(NUM_PHONE, levels = NUM_PHONlevels, labels = NUM_PHONlabels))
    idata <- idata %>% mutate(NUM_CELLS_PARENTS = factor(NUM_CELLS_PARENTS, levels = NUM_PHONlevels, labels = NUM_PHONlabels))
    idata <- idata %>% mutate(NUM_CELLS_HH = factor(NUM_CELLS_HH, levels = NUM_PHONlevels, labels = NUM_PHONlabels))
    idata <- idata %>% mutate(MARITAL2 = factor(MARITAL2, levels = MAR_PUF2_levels, labels = MAR_PUF2_labels))
    
    idata <- idata %>% mutate(P_UTDPCVB13 = factor(P_UTDPCVB13, levels = UTDPCVBlevels, labels = UTDPCVBlabels))
    idata <- idata %>% mutate(EST_GRANT = factor(EST_GRANT, levels = ESTGRANTlevels, labels = ESTGRANTlabels))
    idata <- idata %>% mutate(INS_STAT_I = factor(INS_STAT_I, levels = INS_STAT_Ilevels, labels = INS_STAT_Ilabels))
    idata <- idata %>% mutate(INS_BREAK_I = factor(INS_BREAK_I, levels = INS_BREAK_Ilevels, labels = INS_BREAK_Ilabels))
    idata <- idata %>% mutate(ESTIAP16 = factor(ESTIAP16, levels = ESTIAP16Flevels, labels = ESTIAP16Flabels))
    
    idata <- idata %>% mutate(M_AGEGRP2 = factor(M_AGEGRP2, levels = MAGEGRP2_levels, labels = MAGEGRP2_labels))
    return(idata)
}
