format_char_vars <- function(idata) {
    idata$U3D_HEP <- as.character(idata$U3D_HEP)
    idata$CWIC_02 <- as.character(idata$CWIC_02)
    idata$U2D_HEP <- as.character(idata$U2D_HEP)
    idata$U1D_HEP <- as.character(idata$U1D_HEP)
    idata$P_UTDHEPA1 <- as.character(idata$P_UTDHEPA1)
    
    idata$P_NUMVRX <- as.character(idata$P_NUMVRX)
    idata$P_NUMVRN <- as.character(idata$P_NUMVRN)
    idata$P_NUMVRC <- as.character(idata$P_NUMVRC)
    idata$P_NUMTPN <- as.character(idata$P_NUMTPN)
    idata$P_NUMROT <- as.character(idata$P_NUMROT)
    
    idata$P_NUMRO <- as.character(idata$P_NUMRO)
    idata$P_NUMRM <- as.character(idata$P_NUMRM)
    idata$P_NUMRG <- as.character(idata$P_NUMRG)
    idata$P_NUMRB <- as.character(idata$P_NUMRB)
    idata$P_NUMPOL <- as.character(idata$P_NUMPOL)
    
    idata$P_NUMPCN <- as.character(idata$P_NUMPCN)
    idata$P_NUMPCCN <- as.character(idata$P_NUMPCCN)
    idata$P_NUMPCC13 <- as.character(idata$P_NUMPCC13)
    idata$P_NUMPCC7 <- as.character(idata$P_NUMPCC7)
    idata$P_NUMPCC <- as.character(idata$P_NUMPCC)
    
    idata$P_NUMPCP <- as.character(idata$P_NUMPCP)
    idata$P_NUMPCV <- as.character(idata$P_NUMPCV)
    idata$P_NUMOPV <- as.character(idata$P_NUMOPV)
    idata$P_NUMOLN <- as.character(idata$P_NUMOLN)
    idata$P_NUMMSR <- as.character(idata$P_NUMMSR)
    
    idata$P_NUMMSM <- as.character(idata$P_NUMMSM)
    idata$P_NUMMS <- as.character(idata$P_NUMMS)
    idata$P_NUMMRV <- as.character(idata$P_NUMMRV)
    idata$P_NUMMPR <- as.character(idata$P_NUMMPR)
    idata$P_NUMMP <- as.character(idata$P_NUMMP)
    
    idata$P_NUMMMX <- as.character(idata$P_NUMMMX)
    idata$P_NUMMMRX <- as.character(idata$P_NUMMMRX)
    idata$P_NUMMMR <- as.character(idata$P_NUMMMR)
    idata$P_NUMMCN <- as.character(idata$P_NUMMCN)
    idata$P_NUMIPV <- as.character(idata$P_NUMIPV)
    
    idata$P_NUMHS <- as.character(idata$P_NUMHS)
    idata$P_NUMHM <- as.character(idata$P_NUMHM)
    idata$P_NUMHION <- as.character(idata$P_NUMHION)
    idata$P_NUMHIN <- as.character(idata$P_NUMHIN)
    idata$P_NUMHIB <- as.character(idata$P_NUMHIB)
    
    idata$P_NUMHHY <- as.character(idata$P_NUMHHY)
    idata$P_NUMHG <- as.character(idata$P_NUMHG)
    idata$P_NUMHEP <- as.character(idata$P_NUMHEP)
    idata$P_NUMHEN <- as.character(idata$P_NUMHEN)
    idata$P_NUMHEA <- as.character(idata$P_NUMHEA)
    
    idata$P_NUMFLUN <- as.character(idata$P_NUMFLUN)
    idata$P_NUMFLUM <- as.character(idata$P_NUMFLUM)
    idata$P_NUMFLUL <- as.character(idata$P_NUMFLUL)
    idata$P_NUMFLU <- as.character(idata$P_NUMFLU)
    idata$P_NUMDTP <- as.character(idata$P_NUMDTP)
    
    idata$P_NUMDTA <- as.character(idata$P_NUMDTA)
    idata$P_NUMDIH <- as.character(idata$P_NUMDIH)
    idata$P_NUMDHI <- as.character(idata$P_NUMDHI)
    idata$P_NUMDAH <- as.character(idata$P_NUMDAH)
    idata$P_NUHPHB <- as.character(idata$P_NUHPHB)
    
    idata$P_NUHIBX <- as.character(idata$P_NUHIBX)
    idata$D7 <- as.character(idata$D7)
    idata$D7 <- as.character(idata$D7)
    idata$BFENDFL06 <- as.character(idata$BFENDFL06)
    idata$BFFORMFL06 <- as.character(idata$BFFORMFL06)
    idata$CHILDNM <- as.character(idata$CHILDNM)
    
    idata$CWIC_01 <- as.character(idata$CWIC_01)
    idata$EDUC1 <- as.character(idata$EDUC1)
    idata$I_HISP_K <- as.character(idata$I_HISP_K)
    idata$MOBIL_I <- as.character(idata$MOBIL_I)
    idata$SEX <- as.character(idata$SEX)
    
    idata$INCPOV1 <- as.character(idata$INCPOV1)
    idata$PDAT <- as.character(idata$PDAT)
    idata$PROV_FAC <- as.character(idata$PROV_FAC)
    idata$REGISTRY <- as.character(idata$REGISTRY)
    idata$VFC_ORDER <- as.character(idata$VFC_ORDER)
    
    idata$XDTPTY1 <- as.character(idata$XDTPTY1)
    idata$XVRCTY9 <- as.character(idata$XVRCTY9)
    idata$XVRCTY8 <- as.character(idata$XVRCTY8)
    idata$XVRCTY7 <- as.character(idata$XVRCTY7)
    idata$XVRCTY6 <- as.character(idata$XVRCTY6)
    
    idata$XVRCTY5 <- as.character(idata$XVRCTY5)
    idata$XVRCTY4 <- as.character(idata$XVRCTY4)
    idata$XVRCTY3 <- as.character(idata$XVRCTY3)
    idata$XVRCTY2 <- as.character(idata$XVRCTY2)
    idata$XVRCTY1 <- as.character(idata$XVRCTY1)
    
    idata$XROTTY9 <- as.character(idata$XROTTY9)
    idata$XROTTY8 <- as.character(idata$XROTTY8)
    idata$XROTTY7 <- as.character(idata$XROTTY7)
    idata$XROTTY6 <- as.character(idata$XROTTY6)
    idata$XROTTY5 <- as.character(idata$XROTTY5)
    
    idata$XROTTY4 <- as.character(idata$XROTTY4)
    idata$XROTTY3 <- as.character(idata$XROTTY3)
    idata$XROTTY2 <- as.character(idata$XROTTY2)
    idata$XROTTY1 <- as.character(idata$XROTTY1)
    idata$XPOLTY9 <- as.character(idata$XPOLTY9)
    
    idata$XPOLTY8 <- as.character(idata$XPOLTY8)
    idata$XPOLTY7 <- as.character(idata$XPOLTY7)
    idata$XPOLTY6 <- as.character(idata$XPOLTY6)
    idata$XPOLTY5 <- as.character(idata$XPOLTY5)
    idata$XPOLTY4 <- as.character(idata$XPOLTY4)
    
    idata$XPOLTY3 <- as.character(idata$XPOLTY3)
    idata$XPOLTY2 <- as.character(idata$XPOLTY2)
    idata$XPOLTY1 <- as.character(idata$XPOLTY1)
    idata$XPCVTY9 <- as.character(idata$XPCVTY9)
    idata$XPCVTY8 <- as.character(idata$XPCVTY8)
    
    idata$XPCVTY7 <- as.character(idata$XPCVTY7)
    idata$XPCVTY6 <- as.character(idata$XPCVTY6)
    idata$XPCVTY5 <- as.character(idata$XPCVTY5)
    idata$XPCVTY4 <- as.character(idata$XPCVTY4)
    idata$XPCVTY3 <- as.character(idata$XPCVTY3)
    
    idata$XPCVTY2 <- as.character(idata$XPCVTY2)
    idata$XPCVTY1 <- as.character(idata$XPCVTY1)
    idata$XMMRTY9 <- as.character(idata$XMMRTY9)
    idata$XMMRTY8 <- as.character(idata$XMMRTY8)
    idata$XMMRTY7 <- as.character(idata$XMMRTY7)
    
    idata$XMMRTY6 <- as.character(idata$XMMRTY6)
    idata$XMMRTY5 <- as.character(idata$XMMRTY5)
    idata$XMMRTY4 <- as.character(idata$XMMRTY4)
    idata$XMMRTY3 <- as.character(idata$XMMRTY3)
    idata$XMMRTY2 <- as.character(idata$XMMRTY2)
    
    idata$XMMRTY1 <- as.character(idata$XMMRTY1)
    idata$XHIBTY9 <- as.character(idata$XHIBTY9)
    idata$XHIBTY8 <- as.character(idata$XHIBTY8)
    idata$XHIBTY7 <- as.character(idata$XHIBTY7)
    idata$XHIBTY6 <- as.character(idata$XHIBTY6)
    
    idata$XHIBTY5 <- as.character(idata$XHIBTY5)
    idata$XHIBTY4 <- as.character(idata$XHIBTY4)
    idata$XHIBTY3 <- as.character(idata$XHIBTY3)
    idata$XHIBTY2 <- as.character(idata$XHIBTY2)
    idata$XHIBTY1 <- as.character(idata$XHIBTY1)
    
    idata$XHEPTY9 <- as.character(idata$XHEPTY9)
    idata$XHEPTY8 <- as.character(idata$XHEPTY8)
    idata$XHEPTY7 <- as.character(idata$XHEPTY7)
    idata$XHEPTY6 <- as.character(idata$XHEPTY6)
    idata$XHEPTY5 <- as.character(idata$XHEPTY5)
    
    idata$XHEPTY4 <- as.character(idata$XHEPTY4)
    idata$XHEPTY3 <- as.character(idata$XHEPTY3)
    idata$XHEPTY2 <- as.character(idata$XHEPTY2)
    idata$XHEPTY1 <- as.character(idata$XHEPTY1)
    idata$XFLUTY9 <- as.character(idata$XFLUTY9)
    
    idata$XFLUTY8 <- as.character(idata$XFLUTY8)
    idata$XFLUTY7 <- as.character(idata$XFLUTY7)
    idata$XFLUTY6 <- as.character(idata$XFLUTY6)
    idata$XFLUTY5 <- as.character(idata$XFLUTY5)
    idata$XFLUTY4 <- as.character(idata$XFLUTY4)
    
    idata$XFLUTY3 <- as.character(idata$XFLUTY3)
    idata$XFLUTY2 <- as.character(idata$XFLUTY2)
    idata$XFLUTY1 <- as.character(idata$XFLUTY1)
    idata$XDTPTY9 <- as.character(idata$XDTPTY9)
    idata$XDTPTY8 <- as.character(idata$XDTPTY8)
    
    idata$XDTPTY7 <- as.character(idata$XDTPTY7)
    idata$XDTPTY6 <- as.character(idata$XDTPTY6)
    idata$XDTPTY5 <- as.character(idata$XDTPTY5)
    idata$XDTPTY4 <- as.character(idata$XDTPTY4)
    idata$XDTPTY3 <- as.character(idata$XDTPTY3)
    
    idata$XDTPTY2 <- as.character(idata$XDTPTY2)
    idata$HEP_BRTH <- as.character(idata$HEP_BRTH)
    idata$HEP_FLAG <- as.character(idata$HEP_FLAG)
    idata$P_U12VRC <- as.character(idata$P_U12VRC)
    idata$P_UTD431H_ROUT_S <- as.character(idata$P_UTD431H_ROUT_S)
    
    idata$PUTD4313 <- as.character(idata$PUTD4313)
    idata$P_UTD431H3_ROUT_S <- as.character(idata$P_UTD431H3_ROUT_S)
    idata$PUT43133 <- as.character(idata$PUT43133)
    idata$PU431_314 <- as.character(idata$PU431_314)
    idata$P_UTD431H314_ROUT_S <- as.character(idata$P_UTD431H314_ROUT_S)
    
    idata$PU4313314 <- as.character(idata$PU4313314)
    idata$P_UTD431H313_ROUT_S <- as.character(idata$P_UTD431H313_ROUT_S)
    idata$PU4313313 <- as.character(idata$PU4313313)
    idata$PU431_31 <- as.character(idata$PU431_31)
    idata$P_UTD431H31_ROUT_S <- as.character(idata$P_UTD431H31_ROUT_S)
    
    idata$PU431331 <- as.character(idata$PU431331)
    idata$P_UTDTP4 <- as.character(idata$P_UTDTP4)
    idata$P_UTDTP3 <- as.character(idata$P_UTDTP3)
    idata$P_UTDROT_S <- as.character(idata$P_UTDROT_S)
    idata$P_UTDPOL <- as.character(idata$P_UTDPOL)
    
    idata$P_UTDPCV <- as.character(idata$P_UTDPCV)
    idata$P_UTDPC3 <- as.character(idata$P_UTDPC3)
    idata$P_UTDMMX <- as.character(idata$P_UTDMMX)
    idata$P_UTDMCV <- as.character(idata$P_UTDMCV)
    idata$P_UTDHIB_SHORT_S <- as.character(idata$P_UTDHIB_SHORT_S)
    
    idata$P_UTDHIB_ROUT_S <- as.character(idata$P_UTDHIB_ROUT_S)
    idata$P_UTDHIB <- as.character(idata$P_UTDHIB)
    idata$P_UTDHEPA2 <- as.character(idata$P_UTDHEPA2)
    idata$P_UTDHEP <- as.character(idata$P_UTDHEP)
    idata$P_UTD431 <- as.character(idata$P_UTD431)
    
    idata$P_UTD331 <- as.character(idata$P_UTD331)
    idata$CEN_REG <- as.character(idata$CEN_REG)
    idata$STATE <- as.character(idata$STATE)
    idata$RACE_K <- as.character(idata$RACE_K)
    idata$AGECPOXR <- as.character(idata$AGECPOXR)
    
    idata$C1R <- as.character(idata$C1R)
    idata$C5R <- as.character(idata$C5R)
    idata$INCQ298A <- as.character(idata$INCQ298A)
    idata$RACEETHK <- as.character(idata$RACEETHK)
    idata$D6R <- as.character(idata$D6R)
    
    idata$N_PRVR <- as.character(idata$N_PRVR)
    idata$FRSTBRN <- as.character(idata$FRSTBRN)
    idata$SEQNUMC <- as.character(idata$SEQNUMC)
    idata$SEQNUMHH <- as.character(idata$SEQNUMHH)
    idata$BF_FORMR08 <- as.character(idata$BF_FORMR08)
    
    idata$RENT_OWN <- as.character(idata$RENT_OWN)
    idata$NUM_PHONE <- as.character(idata$NUM_PHONE)
    idata$NUM_CELLS_PARENTS <- as.character(idata$NUM_CELLS_PARENTS)
    idata$NUM_CELLS_HH <- as.character(idata$NUM_CELLS_HH)
    idata$MARITAL2 <- as.character(idata$MARITAL2)
    
    idata$P_UTDPCVB13 <- as.character(idata$P_UTDPCVB13)
    idata$EST_GRANT <- as.character(idata$EST_GRANT)
    idata$INS_STAT_I <- as.character(idata$INS_STAT_I)
    idata$INS_BREAK_I <- as.character(idata$INS_BREAK_I)
    idata$ESTIAP16 <- as.character(idata$ESTIAP16)
    
    idata$M_AGEGRP2 <- as.character(idata$M_AGEGRP2)
    idata$P_NUHEPX <- as.character(idata$P_NUHEPX)
    idata$CBF_01 <- as.character(idata$CBF_01)
    idata$HAD_CPOX <- as.character(idata$HAD_CPOX)
    idata$LANGUAGE <- as.character(idata$LANGUAGE)
    idata$AGEGRP <- as.character(idata$AGEGRP)
    idata$SEQNUMC <- as.character(idata$SEQNUMC)
    idata$SEQNUMHH <- as.character(idata$SEQNUMHH)
    idata$XDTPTY1 <- as.character(idata$XDTPTY1)
    idata$XDTPTY2 <- as.character(idata$XDTPTY2)
    idata$XDTPTY3 <- as.character(idata$XDTPTY3)
    idata$XDTPTY4 <- as.character(idata$XDTPTY4)
    idata$XDTPTY5 <- as.character(idata$XDTPTY5)
    idata$XDTPTY6 <- as.character(idata$XDTPTY6)
    idata$XDTPTY7 <- as.character(idata$XDTPTY7)
    idata$XDTPTY8 <- as.character(idata$XDTPTY8)
    idata$XDTPTY9 <- as.character(idata$XDTPTY9)
    idata$XFLUTY1 <- as.character(idata$XFLUTY1)
    idata$XFLUTY2 <- as.character(idata$XFLUTY2)
    idata$XFLUTY3 <- as.character(idata$XFLUTY3)
    idata$XFLUTY4 <- as.character(idata$XFLUTY4)
    idata$XFLUTY5 <- as.character(idata$XFLUTY5)
    idata$XFLUTY6 <- as.character(idata$XFLUTY6)
    idata$XFLUTY7 <- as.character(idata$XFLUTY7)
    idata$XFLUTY8 <- as.character(idata$XFLUTY8)
    idata$XFLUTY9 <- as.character(idata$XFLUTY9)
    idata$XHEPTY1 <- as.character(idata$XHEPTY1)
    idata$XHEPTY2 <- as.character(idata$XHEPTY2)
    idata$XHEPTY3 <- as.character(idata$XHEPTY3)
    idata$XHEPTY4 <- as.character(idata$XHEPTY4)
    idata$XHEPTY5 <- as.character(idata$XHEPTY5)
    idata$XHEPTY6 <- as.character(idata$XHEPTY6)
    idata$XHEPTY7 <- as.character(idata$XHEPTY7)
    idata$XHEPTY8 <- as.character(idata$XHEPTY8)
    idata$XHEPTY9 <- as.character(idata$XHEPTY9)
    idata$XHIBTY1 <- as.character(idata$XHIBTY1)
    idata$XHIBTY2 <- as.character(idata$XHIBTY2)
    idata$XHIBTY3 <- as.character(idata$XHIBTY3)
    idata$XHIBTY4 <- as.character(idata$XHIBTY4)
    idata$XHIBTY5 <- as.character(idata$XHIBTY5)
    idata$XHIBTY6 <- as.character(idata$XHIBTY6)
    idata$XHIBTY7 <- as.character(idata$XHIBTY7)
    idata$XHIBTY8 <- as.character(idata$XHIBTY8)
    idata$XHIBTY9 <- as.character(idata$XHIBTY9)
    idata$XMMRTY1 <- as.character(idata$XMMRTY1)
    idata$XMMRTY2 <- as.character(idata$XMMRTY2)
    idata$XMMRTY3 <- as.character(idata$XMMRTY3)
    idata$XMMRTY4 <- as.character(idata$XMMRTY4)
    idata$XMMRTY5 <- as.character(idata$XMMRTY5)
    idata$XMMRTY6 <- as.character(idata$XMMRTY6)
    idata$XMMRTY7 <- as.character(idata$XMMRTY7)
    idata$XMMRTY8 <- as.character(idata$XMMRTY8)
    idata$XMMRTY9 <- as.character(idata$XMMRTY9)
    idata$XPCVTY1 <- as.character(idata$XPCVTY1)
    idata$XPCVTY2 <- as.character(idata$XPCVTY2)
    idata$XPCVTY3 <- as.character(idata$XPCVTY3)
    idata$XPCVTY4 <- as.character(idata$XPCVTY4)
    idata$XPCVTY5 <- as.character(idata$XPCVTY5)
    idata$XPCVTY6 <- as.character(idata$XPCVTY6)
    idata$XPCVTY7 <- as.character(idata$XPCVTY7)
    idata$XPCVTY8 <- as.character(idata$XPCVTY8)
    idata$XPCVTY9 <- as.character(idata$XPCVTY9)
    idata$XPOLTY1 <- as.character(idata$XPOLTY1)
    idata$XPOLTY2 <- as.character(idata$XPOLTY2)
    idata$XPOLTY3 <- as.character(idata$XPOLTY3)
    idata$XPOLTY4 <- as.character(idata$XPOLTY4)
    idata$XPOLTY5 <- as.character(idata$XPOLTY5)
    idata$XPOLTY6 <- as.character(idata$XPOLTY6)
    idata$XPOLTY7 <- as.character(idata$XPOLTY7)
    idata$XPOLTY8 <- as.character(idata$XPOLTY8)
    idata$XPOLTY9 <- as.character(idata$XPOLTY9)
    idata$XROTTY1 <- as.character(idata$XROTTY1)
    idata$XROTTY2 <- as.character(idata$XROTTY2)
    idata$XROTTY3 <- as.character(idata$XROTTY3)
    idata$XROTTY4 <- as.character(idata$XROTTY4)
    idata$XROTTY5 <- as.character(idata$XROTTY5)
    idata$XROTTY6 <- as.character(idata$XROTTY6)
    idata$XROTTY7 <- as.character(idata$XROTTY7)
    idata$XROTTY8 <- as.character(idata$XROTTY8)
    idata$XROTTY9 <- as.character(idata$XROTTY9)
    idata$XVRCTY1 <- as.character(idata$XVRCTY1)
    idata$XVRCTY2 <- as.character(idata$XVRCTY2)
    idata$XVRCTY3 <- as.character(idata$XVRCTY3)
    idata$XVRCTY4 <- as.character(idata$XVRCTY4)
    idata$XVRCTY5 <- as.character(idata$XVRCTY5)
    idata$XVRCTY6 <- as.character(idata$XVRCTY6)
    idata$XVRCTY7 <- as.character(idata$XVRCTY7)
    idata$XVRCTY8 <- as.character(idata$XVRCTY8)
    idata$XVRCTY9 <- as.character(idata$XVRCTY9)
    return(idata)
}
