format_char_vars <- function(df) {
    df$U3D_HEP <- as.character(df$U3D_HEP)
    df$CWIC_02 <- as.character(df$CWIC_02)
    df$U2D_HEP <- as.character(df$U2D_HEP)
    df$U1D_HEP <- as.character(df$U1D_HEP)
    df$P_UTDHEPA1 <- as.character(df$P_UTDHEPA1)
    
    df$P_NUMVRX <- as.character(df$P_NUMVRX)
    df$P_NUMVRN <- as.character(df$P_NUMVRN)
    df$P_NUMVRC <- as.character(df$P_NUMVRC)
    df$P_NUMTPN <- as.character(df$P_NUMTPN)
    df$P_NUMROT <- as.character(df$P_NUMROT)
    
    df$P_NUMRO <- as.character(df$P_NUMRO)
    df$P_NUMRM <- as.character(df$P_NUMRM)
    df$P_NUMRG <- as.character(df$P_NUMRG)
    df$P_NUMRB <- as.character(df$P_NUMRB)
    df$P_NUMPOL <- as.character(df$P_NUMPOL)
    
    df$P_NUMPCN <- as.character(df$P_NUMPCN)
    df$P_NUMPCCN <- as.character(df$P_NUMPCCN)
    df$P_NUMPCC13 <- as.character(df$P_NUMPCC13)
    df$P_NUMPCC7 <- as.character(df$P_NUMPCC7)
    df$P_NUMPCC <- as.character(df$P_NUMPCC)
    
    df$P_NUMPCP <- as.character(df$P_NUMPCP)
    df$P_NUMPCV <- as.character(df$P_NUMPCV)
    df$P_NUMOPV <- as.character(df$P_NUMOPV)
    df$P_NUMOLN <- as.character(df$P_NUMOLN)
    df$P_NUMMSR <- as.character(df$P_NUMMSR)
    
    df$P_NUMMSM <- as.character(df$P_NUMMSM)
    df$P_NUMMS <- as.character(df$P_NUMMS)
    df$P_NUMMRV <- as.character(df$P_NUMMRV)
    df$P_NUMMPR <- as.character(df$P_NUMMPR)
    df$P_NUMMP <- as.character(df$P_NUMMP)
    
    df$P_NUMMMX <- as.character(df$P_NUMMMX)
    df$P_NUMMMRX <- as.character(df$P_NUMMMRX)
    df$P_NUMMMR <- as.character(df$P_NUMMMR)
    df$P_NUMMCN <- as.character(df$P_NUMMCN)
    df$P_NUMIPV <- as.character(df$P_NUMIPV)
    
    df$P_NUMHS <- as.character(df$P_NUMHS)
    df$P_NUMHM <- as.character(df$P_NUMHM)
    df$P_NUMHION <- as.character(df$P_NUMHION)
    df$P_NUMHIN <- as.character(df$P_NUMHIN)
    df$P_NUMHIB <- as.character(df$P_NUMHIB)
    
    df$P_NUMHHY <- as.character(df$P_NUMHHY)
    df$P_NUMHG <- as.character(df$P_NUMHG)
    df$P_NUMHEP <- as.character(df$P_NUMHEP)
    df$P_NUMHEN <- as.character(df$P_NUMHEN)
    df$P_NUMHEA <- as.character(df$P_NUMHEA)
    
    df$P_NUMFLUN <- as.character(df$P_NUMFLUN)
    df$P_NUMFLUM <- as.character(df$P_NUMFLUM)
    df$P_NUMFLUL <- as.character(df$P_NUMFLUL)
    df$P_NUMFLU <- as.character(df$P_NUMFLU)
    df$P_NUMDTP <- as.character(df$P_NUMDTP)
    
    df$P_NUMDTA <- as.character(df$P_NUMDTA)
    df$P_NUMDIH <- as.character(df$P_NUMDIH)
    df$P_NUMDHI <- as.character(df$P_NUMDHI)
    df$P_NUMDAH <- as.character(df$P_NUMDAH)
    df$P_NUHPHB <- as.character(df$P_NUHPHB)
    
    df$P_NUHIBX <- as.character(df$P_NUHIBX)
    df$D7 <- as.character(df$D7)
    df$D7 <- as.character(df$D7)
    df$BFENDFL06 <- as.character(df$BFENDFL06)
    df$BFFORMFL06 <- as.character(df$BFFORMFL06)
    df$CHILDNM <- as.character(df$CHILDNM)
    
    df$CWIC_01 <- as.character(df$CWIC_01)
    df$EDUC1 <- as.character(df$EDUC1)
    df$I_HISP_K <- as.character(df$I_HISP_K)
    df$MOBIL_I <- as.character(df$MOBIL_I)
    df$SEX <- as.character(df$SEX)
    
    df$INCPOV1 <- as.character(df$INCPOV1)
    df$PDAT <- as.character(df$PDAT)
    df$PROV_FAC <- as.character(df$PROV_FAC)
    df$REGISTRY <- as.character(df$REGISTRY)
    df$VFC_ORDER <- as.character(df$VFC_ORDER)
    
    df$XDTPTY1 <- as.character(df$XDTPTY1)
    df$XVRCTY9 <- as.character(df$XVRCTY9)
    df$XVRCTY8 <- as.character(df$XVRCTY8)
    df$XVRCTY7 <- as.character(df$XVRCTY7)
    df$XVRCTY6 <- as.character(df$XVRCTY6)
    
    df$XVRCTY5 <- as.character(df$XVRCTY5)
    df$XVRCTY4 <- as.character(df$XVRCTY4)
    df$XVRCTY3 <- as.character(df$XVRCTY3)
    df$XVRCTY2 <- as.character(df$XVRCTY2)
    df$XVRCTY1 <- as.character(df$XVRCTY1)
    
    df$XROTTY9 <- as.character(df$XROTTY9)
    df$XROTTY8 <- as.character(df$XROTTY8)
    df$XROTTY7 <- as.character(df$XROTTY7)
    df$XROTTY6 <- as.character(df$XROTTY6)
    df$XROTTY5 <- as.character(df$XROTTY5)
    
    df$XROTTY4 <- as.character(df$XROTTY4)
    df$XROTTY3 <- as.character(df$XROTTY3)
    df$XROTTY2 <- as.character(df$XROTTY2)
    df$XROTTY1 <- as.character(df$XROTTY1)
    df$XPOLTY9 <- as.character(df$XPOLTY9)
    
    df$XPOLTY8 <- as.character(df$XPOLTY8)
    df$XPOLTY7 <- as.character(df$XPOLTY7)
    df$XPOLTY6 <- as.character(df$XPOLTY6)
    df$XPOLTY5 <- as.character(df$XPOLTY5)
    df$XPOLTY4 <- as.character(df$XPOLTY4)
    
    df$XPOLTY3 <- as.character(df$XPOLTY3)
    df$XPOLTY2 <- as.character(df$XPOLTY2)
    df$XPOLTY1 <- as.character(df$XPOLTY1)
    df$XPCVTY9 <- as.character(df$XPCVTY9)
    df$XPCVTY8 <- as.character(df$XPCVTY8)
    
    df$XPCVTY7 <- as.character(df$XPCVTY7)
    df$XPCVTY6 <- as.character(df$XPCVTY6)
    df$XPCVTY5 <- as.character(df$XPCVTY5)
    df$XPCVTY4 <- as.character(df$XPCVTY4)
    df$XPCVTY3 <- as.character(df$XPCVTY3)
    
    df$XPCVTY2 <- as.character(df$XPCVTY2)
    df$XPCVTY1 <- as.character(df$XPCVTY1)
    df$XMMRTY9 <- as.character(df$XMMRTY9)
    df$XMMRTY8 <- as.character(df$XMMRTY8)
    df$XMMRTY7 <- as.character(df$XMMRTY7)
    
    df$XMMRTY6 <- as.character(df$XMMRTY6)
    df$XMMRTY5 <- as.character(df$XMMRTY5)
    df$XMMRTY4 <- as.character(df$XMMRTY4)
    df$XMMRTY3 <- as.character(df$XMMRTY3)
    df$XMMRTY2 <- as.character(df$XMMRTY2)
    
    df$XMMRTY1 <- as.character(df$XMMRTY1)
    df$XHIBTY9 <- as.character(df$XHIBTY9)
    df$XHIBTY8 <- as.character(df$XHIBTY8)
    df$XHIBTY7 <- as.character(df$XHIBTY7)
    df$XHIBTY6 <- as.character(df$XHIBTY6)
    
    df$XHIBTY5 <- as.character(df$XHIBTY5)
    df$XHIBTY4 <- as.character(df$XHIBTY4)
    df$XHIBTY3 <- as.character(df$XHIBTY3)
    df$XHIBTY2 <- as.character(df$XHIBTY2)
    df$XHIBTY1 <- as.character(df$XHIBTY1)
    
    df$XHEPTY9 <- as.character(df$XHEPTY9)
    df$XHEPTY8 <- as.character(df$XHEPTY8)
    df$XHEPTY7 <- as.character(df$XHEPTY7)
    df$XHEPTY6 <- as.character(df$XHEPTY6)
    df$XHEPTY5 <- as.character(df$XHEPTY5)
    
    df$XHEPTY4 <- as.character(df$XHEPTY4)
    df$XHEPTY3 <- as.character(df$XHEPTY3)
    df$XHEPTY2 <- as.character(df$XHEPTY2)
    df$XHEPTY1 <- as.character(df$XHEPTY1)
    df$XFLUTY9 <- as.character(df$XFLUTY9)
    
    df$XFLUTY8 <- as.character(df$XFLUTY8)
    df$XFLUTY7 <- as.character(df$XFLUTY7)
    df$XFLUTY6 <- as.character(df$XFLUTY6)
    df$XFLUTY5 <- as.character(df$XFLUTY5)
    df$XFLUTY4 <- as.character(df$XFLUTY4)
    
    df$XFLUTY3 <- as.character(df$XFLUTY3)
    df$XFLUTY2 <- as.character(df$XFLUTY2)
    df$XFLUTY1 <- as.character(df$XFLUTY1)
    df$XDTPTY9 <- as.character(df$XDTPTY9)
    df$XDTPTY8 <- as.character(df$XDTPTY8)
    
    df$XDTPTY7 <- as.character(df$XDTPTY7)
    df$XDTPTY6 <- as.character(df$XDTPTY6)
    df$XDTPTY5 <- as.character(df$XDTPTY5)
    df$XDTPTY4 <- as.character(df$XDTPTY4)
    df$XDTPTY3 <- as.character(df$XDTPTY3)
    
    df$XDTPTY2 <- as.character(df$XDTPTY2)
    df$HEP_BRTH <- as.character(df$HEP_BRTH)
    df$HEP_FLAG <- as.character(df$HEP_FLAG)
    df$P_U12VRC <- as.character(df$P_U12VRC)
    df$P_UTD431H_ROUT_S <- as.character(df$P_UTD431H_ROUT_S)
    
    df$PUTD4313 <- as.character(df$PUTD4313)
    df$P_UTD431H3_ROUT_S <- as.character(df$P_UTD431H3_ROUT_S)
    df$PUT43133 <- as.character(df$PUT43133)
    df$PU431_314 <- as.character(df$PU431_314)
    df$P_UTD431H314_ROUT_S <- as.character(df$P_UTD431H314_ROUT_S)
    
    df$PU4313314 <- as.character(df$PU4313314)
    df$P_UTD431H313_ROUT_S <- as.character(df$P_UTD431H313_ROUT_S)
    df$PU4313313 <- as.character(df$PU4313313)
    df$PU431_31 <- as.character(df$PU431_31)
    df$P_UTD431H31_ROUT_S <- as.character(df$P_UTD431H31_ROUT_S)
    
    df$PU431331 <- as.character(df$PU431331)
    df$P_UTDTP4 <- as.character(df$P_UTDTP4)
    df$P_UTDTP3 <- as.character(df$P_UTDTP3)
    df$P_UTDROT_S <- as.character(df$P_UTDROT_S)
    df$P_UTDPOL <- as.character(df$P_UTDPOL)
    
    df$P_UTDPCV <- as.character(df$P_UTDPCV)
    df$P_UTDPC3 <- as.character(df$P_UTDPC3)
    df$P_UTDMMX <- as.character(df$P_UTDMMX)
    df$P_UTDMCV <- as.character(df$P_UTDMCV)
    df$P_UTDHIB_SHORT_S <- as.character(df$P_UTDHIB_SHORT_S)
    
    df$P_UTDHIB_ROUT_S <- as.character(df$P_UTDHIB_ROUT_S)
    df$P_UTDHIB <- as.character(df$P_UTDHIB)
    df$P_UTDHEPA2 <- as.character(df$P_UTDHEPA2)
    df$P_UTDHEP <- as.character(df$P_UTDHEP)
    df$P_UTD431 <- as.character(df$P_UTD431)
    
    df$P_UTD331 <- as.character(df$P_UTD331)
    df$CEN_REG <- as.character(df$CEN_REG)
    df$STATE <- as.character(df$STATE)
    df$RACE_K <- as.character(df$RACE_K)
    df$AGECPOXR <- as.character(df$AGECPOXR)
    
    df$C1R <- as.character(df$C1R)
    df$C5R <- as.character(df$C5R)
    df$INCQ298A <- as.character(df$INCQ298A)
    df$RACEETHK <- as.character(df$RACEETHK)
    df$D6R <- as.character(df$D6R)
    
    df$N_PRVR <- as.character(df$N_PRVR)
    df$FRSTBRN <- as.character(df$FRSTBRN)
    df$SEQNUMC <- as.character(df$SEQNUMC)
    df$SEQNUMHH <- as.character(df$SEQNUMHH)
    df$BF_FORMR08 <- as.character(df$BF_FORMR08)
    
    df$RENT_OWN <- as.character(df$RENT_OWN)
    df$NUM_PHONE <- as.character(df$NUM_PHONE)
    df$NUM_CELLS_PARENTS <- as.character(df$NUM_CELLS_PARENTS)
    df$NUM_CELLS_HH <- as.character(df$NUM_CELLS_HH)
    df$MARITAL2 <- as.character(df$MARITAL2)
    
    df$P_UTDPCVB13 <- as.character(df$P_UTDPCVB13)
    df$EST_GRANT <- as.character(df$EST_GRANT)
    df$INS_STAT_I <- as.character(df$INS_STAT_I)
    df$INS_BREAK_I <- as.character(df$INS_BREAK_I)
    df$ESTIAP16 <- as.character(df$ESTIAP16)
    
    df$M_AGEGRP2 <- as.character(df$M_AGEGRP2)
    df$P_NUHEPX <- as.character(df$P_NUHEPX)
    df$CBF_01 <- as.character(df$CBF_01)
    df$HAD_CPOX <- as.character(df$HAD_CPOX)
    df$LANGUAGE <- as.character(df$LANGUAGE)
    df$AGEGRP <- as.character(df$AGEGRP)
    df$SEQNUMC <- as.character(df$SEQNUMC)
    df$SEQNUMHH <- as.character(df$SEQNUMHH)
    df$XDTPTY1 <- as.character(df$XDTPTY1)
    df$XDTPTY2 <- as.character(df$XDTPTY2)
    df$XDTPTY3 <- as.character(df$XDTPTY3)
    df$XDTPTY4 <- as.character(df$XDTPTY4)
    df$XDTPTY5 <- as.character(df$XDTPTY5)
    df$XDTPTY6 <- as.character(df$XDTPTY6)
    df$XDTPTY7 <- as.character(df$XDTPTY7)
    df$XDTPTY8 <- as.character(df$XDTPTY8)
    df$XDTPTY9 <- as.character(df$XDTPTY9)
    df$XFLUTY1 <- as.character(df$XFLUTY1)
    df$XFLUTY2 <- as.character(df$XFLUTY2)
    df$XFLUTY3 <- as.character(df$XFLUTY3)
    df$XFLUTY4 <- as.character(df$XFLUTY4)
    df$XFLUTY5 <- as.character(df$XFLUTY5)
    df$XFLUTY6 <- as.character(df$XFLUTY6)
    df$XFLUTY7 <- as.character(df$XFLUTY7)
    df$XFLUTY8 <- as.character(df$XFLUTY8)
    df$XFLUTY9 <- as.character(df$XFLUTY9)
    df$XHEPTY1 <- as.character(df$XHEPTY1)
    df$XHEPTY2 <- as.character(df$XHEPTY2)
    df$XHEPTY3 <- as.character(df$XHEPTY3)
    df$XHEPTY4 <- as.character(df$XHEPTY4)
    df$XHEPTY5 <- as.character(df$XHEPTY5)
    df$XHEPTY6 <- as.character(df$XHEPTY6)
    df$XHEPTY7 <- as.character(df$XHEPTY7)
    df$XHEPTY8 <- as.character(df$XHEPTY8)
    df$XHEPTY9 <- as.character(df$XHEPTY9)
    df$XHIBTY1 <- as.character(df$XHIBTY1)
    df$XHIBTY2 <- as.character(df$XHIBTY2)
    df$XHIBTY3 <- as.character(df$XHIBTY3)
    df$XHIBTY4 <- as.character(df$XHIBTY4)
    df$XHIBTY5 <- as.character(df$XHIBTY5)
    df$XHIBTY6 <- as.character(df$XHIBTY6)
    df$XHIBTY7 <- as.character(df$XHIBTY7)
    df$XHIBTY8 <- as.character(df$XHIBTY8)
    df$XHIBTY9 <- as.character(df$XHIBTY9)
    df$XMMRTY1 <- as.character(df$XMMRTY1)
    df$XMMRTY2 <- as.character(df$XMMRTY2)
    df$XMMRTY3 <- as.character(df$XMMRTY3)
    df$XMMRTY4 <- as.character(df$XMMRTY4)
    df$XMMRTY5 <- as.character(df$XMMRTY5)
    df$XMMRTY6 <- as.character(df$XMMRTY6)
    df$XMMRTY7 <- as.character(df$XMMRTY7)
    df$XMMRTY8 <- as.character(df$XMMRTY8)
    df$XMMRTY9 <- as.character(df$XMMRTY9)
    df$XPCVTY1 <- as.character(df$XPCVTY1)
    df$XPCVTY2 <- as.character(df$XPCVTY2)
    df$XPCVTY3 <- as.character(df$XPCVTY3)
    df$XPCVTY4 <- as.character(df$XPCVTY4)
    df$XPCVTY5 <- as.character(df$XPCVTY5)
    df$XPCVTY6 <- as.character(df$XPCVTY6)
    df$XPCVTY7 <- as.character(df$XPCVTY7)
    df$XPCVTY8 <- as.character(df$XPCVTY8)
    df$XPCVTY9 <- as.character(df$XPCVTY9)
    df$XPOLTY1 <- as.character(df$XPOLTY1)
    df$XPOLTY2 <- as.character(df$XPOLTY2)
    df$XPOLTY3 <- as.character(df$XPOLTY3)
    df$XPOLTY4 <- as.character(df$XPOLTY4)
    df$XPOLTY5 <- as.character(df$XPOLTY5)
    df$XPOLTY6 <- as.character(df$XPOLTY6)
    df$XPOLTY7 <- as.character(df$XPOLTY7)
    df$XPOLTY8 <- as.character(df$XPOLTY8)
    df$XPOLTY9 <- as.character(df$XPOLTY9)
    df$XROTTY1 <- as.character(df$XROTTY1)
    df$XROTTY2 <- as.character(df$XROTTY2)
    df$XROTTY3 <- as.character(df$XROTTY3)
    df$XROTTY4 <- as.character(df$XROTTY4)
    df$XROTTY5 <- as.character(df$XROTTY5)
    df$XROTTY6 <- as.character(df$XROTTY6)
    df$XROTTY7 <- as.character(df$XROTTY7)
    df$XROTTY8 <- as.character(df$XROTTY8)
    df$XROTTY9 <- as.character(df$XROTTY9)
    df$XVRCTY1 <- as.character(df$XVRCTY1)
    df$XVRCTY2 <- as.character(df$XVRCTY2)
    df$XVRCTY3 <- as.character(df$XVRCTY3)
    df$XVRCTY4 <- as.character(df$XVRCTY4)
    df$XVRCTY5 <- as.character(df$XVRCTY5)
    df$XVRCTY6 <- as.character(df$XVRCTY6)
    df$XVRCTY7 <- as.character(df$XVRCTY7)
    df$XVRCTY8 <- as.character(df$XVRCTY8)
    df$XVRCTY9 <- as.character(df$XVRCTY9)
    #fixing mistakes above the klugey way:
    #df <- df %>% mutate(dflu5 = as.numeric(dflu5))
    df <- df %>% mutate(DFLU6 = as.numeric(DFLU6))
    df <- df %>% mutate(DHEPB6 = as.numeric(DHEPB6))
    df <- df %>% mutate(DHEPB7 = as.numeric(DHEPB7))
    df <- df %>% mutate(DPCV6 = as.numeric(DPCV6))
    df <- df %>% mutate(DPOLIO6 = as.numeric(DPOLIO6))
    df <- df %>% mutate(DROT4 = as.numeric(DROT4))
    df <- df %>% mutate(DVRC3 = as.numeric(DVRC3))
    df <- df %>% mutate(FLU5_AGE = as.numeric(FLU5_AGE))
    df <- df %>% mutate(FLU6_AGE = as.numeric(FLU6_AGE))
    df <- df %>% mutate(HEA4_AGE = as.numeric(HEA4_AGE))
    df <- df %>% mutate(HEP6_AGE = as.numeric(HEP6_AGE))
    df <- df %>% mutate(PCV6_AGE = as.numeric(PCV6_AGE))
    df <- df %>% mutate(POL6_AGE = as.numeric(POL6_AGE))
    df <- df %>% mutate(ROT4_AGE = as.numeric(ROT4_AGE))
    df <- df %>% mutate(VRC3_AGE = as.numeric(VRC3_AGE))
    df <- df %>% mutate(DHEPA4 = as.numeric(DHEPA4))
    return(df)
}
