var_labels <- function(df) {
    var_label(df$ins_break_i) <- "Continuity of insurance since birth"
    var_label(df$ins_stat_i) <- "Insurance status"
    var_label(df$vrc2_age) <- "Age in Months at Varicella #2"
    var_label(df$vrc1_age) <- "Age in Months at Varicella #1"
    var_label(df$rot4_age) <- "Age in Months at Rotavirus #4"
    var_label(df$rot3_age) <- "Age in Months at Rotavirus #3"
    var_label(df$rot2_age) <- "Age in Months at Rotavirus #2"
    var_label(df$rot1_age) <- "Age in Months at Rotavirus #1"
    var_label(df$pol5_age) <- "Age in Months at Polio #5"
    var_label(df$pol4_age) <- "Age in Months at Polio #4"
    var_label(df$pol3_age) <- "Age in Months at Polio #3"
    var_label(df$pol2_age) <- "Age in Months at Polio #2"
    var_label(df$pol1_age) <- "Age in Months at Polio #1"
    var_label(df$pcv5_age) <- "Age in Months at Pneumococcal #5"
    var_label(df$pcv4_age) <- "Age in Months at Pneumococcal #4"
    var_label(df$pcv3_age) <- "Age in Months at Pneumococcal #3"
    var_label(df$pcv2_age) <- "Age in Months at Pneumococcal #2"
    var_label(df$pcv1_age) <- "Age in Months at Pneumococcal #1"
    var_label(df$mmr3_age) <- "Age in Months at Measles #3"
    var_label(df$mmr2_age) <- "Age in Months at Measles #2"
    var_label(df$mmr1_age) <- "Age in Months at Measles #1"
    var_label(df$hib6_age) <- "Age in Months at hib #6"
    var_label(df$hib5_age) <- "Age in Months at hib #5"
    var_label(df$hib4_age) <- "Age in Months at hib #4"
    var_label(df$hib3_age) <- "Age in Months at hib #3"
    var_label(df$hib2_age) <- "Age in Months at hib #2"
    var_label(df$hib1_age) <- "Age in Months at hib #1"
    var_label(df$hep5_age) <- "Age in Months at Hep B #5"
    var_label(df$hep4_age) <- "Age in Months at Hep B #4"
    var_label(df$hep3_age) <- "Age in Months at Hep B #3"
    var_label(df$hep2_age) <- "Age in Months at Hep B #2"
    var_label(df$hep1_age) <- "Age in Months at Hep B #1"
    var_label(df$hea2_age) <- "Age in Months at Hepatitis A #2"
    var_label(df$hea1_age) <- "Age in Months at Hepatitis A #1"
    var_label(df$flu6_age) <- "Age in Months at Flu #6"
    var_label(df$flu5_age) <- "Age in Months at Flu #5"
    var_label(df$flu4_age) <- "Age in Months at Flu #4"
    var_label(df$flu3_age) <- "Age in Months at Flu #3"
    var_label(df$flu2_age) <- "Age in Months at Flu #2"
    var_label(df$flu1_age) <- "Age in Months at Flu #1"
    var_label(df$dtp5_age) <- "Age in Months at DT #5"
    var_label(df$dtp4_age) <- "Age in Months at DT #4"
    var_label(df$dtp3_age) <- "Age in Months at DT #3"
    var_label(df$dtp2_age) <- "Age in Months at DT #2"
    var_label(df$dtp1_age) <- "Age in Months at DT #1"
    var_label(df$dvrc3) <- "Age in days at Prov-reptd Varicella #3"
    var_label(df$dvrc2) <- "Age in days at Prov-reptd Varicella #2"
    var_label(df$dvrc1) <- "Age in days at Prov-reptd Varicella #1"
    var_label(df$drot4) <- "Age in days at Prov-reptd Rotavirus #4"
    var_label(df$drot3) <- "Age in days at Prov-reptd Rotavirus #3"
    var_label(df$drot2) <- "Age in days at Prov-reptd Rotavirus #2"
    var_label(df$drot1) <- "Age in days at Prov-reptd Rotavirus #1"
    var_label(df$dpolio6) <- "Age in days at Prov-reptd Polio #6"
    var_label(df$dpolio5) <- "Age in days at Prov-reptd Polio #5"
    var_label(df$dpolio4) <- "Age in days at Prov-reptd Polio #4"
    var_label(df$dpolio3) <- "Age in days at Prov-reptd Polio #3"
    var_label(df$dpolio2) <- "Age in days at Prov-reptd Polio #2"
    var_label(df$dpolio1) <- "Age in days at Prov-reptd Polio #1"
    var_label(df$dpcv6) <- "Age in days at Prov-reptd Pneumococcal #6"
    var_label(df$dpcv5) <- "Age in days at Prov-reptd Pneumococcal #5"
    var_label(df$dpcv4) <- "Age in days at Prov-reptd Pneumococcal #4"
    var_label(df$dpcv3) <- "Age in days at Prov-reptd Pneumococcal #3"
    var_label(df$dpcv2) <- "Age in days at Prov-reptd Pneumococcal #2"
    var_label(df$dpcv1) <- "Age in days at Prov-reptd Pneumococcal #1"
    var_label(df$dmmr3) <- "Age in days at Prov-reptd Measles #3"
    var_label(df$dmmr2) <- "Age in days at Prov-reptd Measles #2"
    var_label(df$dmmr1) <- "Age in days at Prov-reptd Measles #1"
    var_label(df$dhib6) <- "Age in days at Prov-reptd hib #6"
    var_label(df$dhib5) <- "Age in days at Prov-reptd hib #5"
    var_label(df$dhib4) <- "Age in days at Prov-reptd hib #4"
    var_label(df$dhib3) <- "Age in days at Prov-reptd hib #3"
    var_label(df$dhib2) <- "Age in days at Prov-reptd hib #2"
    var_label(df$dhib1) <- "Age in days at Prov-reptd hib #1"
    var_label(df$dhepb7) <- "Age in days at Prov-reptd Hep B #7"
    var_label(df$dhepb6) <- "Age in days at Prov-reptd Hep B #6"
    var_label(df$dhepb5) <- "Age in days at Prov-reptd Hep B #5"
    var_label(df$dhepb4) <- "Age in days at Prov-reptd Hep B #4"
    var_label(df$dhepb3) <- "Age in days at Prov-reptd Hep B #3"
    var_label(df$dhepb2) <- "Age in days at Prov-reptd Hep B #2"
    var_label(df$dhepb1) <- "Age in days at Prov-reptd Hep B #1"
    var_label(df$dhepa4) <- "Age in days at Prov-reptd Hepatitis A #4"
    var_label(df$dhepa3) <- "Age in days at Prov-reptd Hepatitis A #3"
    var_label(df$dhepa2) <- "Age in days at Prov-reptd Hepatitis A #2"
    var_label(df$dhepa1) <- "Age in days at Prov-reptd Hepatitis A #1"
    var_label(df$dflu6) <- "Age in days at Prov-reptd Flu #6"
    var_label(df$dflu5) <- "Age in days at Prov-reptd Flu #5"
    var_label(df$dflu4) <- "Age in days at Prov-reptd Flu #4"
    var_label(df$dflu3) <- "Age in days at Prov-reptd Flu #3"
    var_label(df$dflu2) <- "Age in days at Prov-reptd Flu #2"
    var_label(df$dflu1) <- "Age in days at Prov-reptd Flu #1"
    var_label(df$ddtp6) <- "Age in days at Prov-reptd DT #6"
    var_label(df$ddtp5) <- "Age in days at Prov-reptd DT #5"
    var_label(df$ddtp4) <- "Age in days at Prov-reptd DT #4"
    var_label(df$ddtp3) <- "Age in days at Prov-reptd DT #3"
    var_label(df$ddtp2) <- "Age in days at Prov-reptd DT #2"
    var_label(df$ddtp1) <- "Age in days at Prov-reptd DT #1"
    var_label(df$hep_brth) <- "Hep B at birth?"
    var_label(df$registry) <- "Providers reported vaccine data to registry"
    var_label(df$prov_fac) <- "Provider facility types"
    var_label(df$n_prvr) <- "Number of providers with vaccine data"
    var_label(df$state) <- "State"
    var_label(df$sex) <- "Child's Gender"
    var_label(df$rent_own) <- "Rent, own, etc."
    var_label(df$raceethk) <- "Child's race"
    var_label(df$num_cells_parents) <- "How many cells phones for parents?"
    var_label(df$num_cells_hh) <- "How many cell phones in household?"
    var_label(df$mobil_i) <- "Child born in different state?"
    var_label(df$marital2) <- "Mom's marital status"
    var_label(df$m_agegrp2) <- "Mom's age group"
    var_label(df$language) <- "Interview language"
    var_label(df$incpov1) <- "Poverty Status"
    var_label(df$i_hisp_k) <- "Is the child Hispanic?"
    var_label(df$frstbrn) <- "Is the child a first-born?"
    var_label(df$educ1) <- "Mother's education level"
    var_label(df$cwic_02) <- "Child receiving WIC benefits?"
    var_label(df$cwic_01) <- "Child ever received WIC benefits?"
    var_label(df$childnm) <- "Number of children in household"
    var_label(df$cbf_01) <- "Was child either breastfed or fed breast milk?"
    var_label(df$c5r) <- "Respondent"
    var_label(df$c1r) <- "Number of people in household"
    var_label(df$agegrp) <- "Child's Age Group"
    var_label(df$had_cpox) <- "Ever had chicken pox?"
    var_label(df$seqnumhh) <- "Household"
    var_label(df$seqnumc) <- "Child ID"
    df <- rename(df, child_race = raceethk)
    df <- rename(df, born_diff = mobil_i)
    df <- rename(df, mom_mar = marital2)
    df <- rename(df, mom_age = m_agegrp2)
    df <- rename(df, poverty = incpov1)
    df <- rename(df, mom_ed = educ1)
    df <- rename(df, wic = cwic_02)
    df <- rename(df, wic_ever = cwic_01)
    df <- rename(df, respondent = c5r)
    df <- rename(df, num_hh = c1r)
}
